name: PHP Sniff and Merge Workflow

on:
  pull_request:
    branches:
      - main
      - test_branch

jobs:
  phpsniff_and_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install Composer dependencies
        run: composer install --prefer-dist

      - name: Run phpcs and capture output
        id: phpcs
        run: |
          ls -la  # List files in the current directory for debugging
          PHPCS_OUTPUT=$(php vendor/bin/phpcs --standard=Generic --sniffs=Generic.Metrics.CyclomaticComplexity web 2>&1) || true
          echo "$PHPCS_OUTPUT"  # Print the output for debugging
          echo "PHPCS_OUTPUT=$PHPCS_OUTPUT" >> $GITHUB_ENV
          exit 0  # Add this line to ensure the script continues, even if PHP CodeSniffer exits with an error

      - name: Check for errors
        run: |
          if [ -n "${{ env.PHPCS_OUTPUT }}" ]; then
            echo "PHP CodeSniffer found errors:"
            echo "${{ env.PHPCS_OUTPUT }}"
            exit 1
          fi

      - name: Merge pull request
        if: success()
        uses: repo-sync/pull-request@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          method: merge
